Semaphore
rafael2ll/sdql-service pull request #2
Opened 2020-11-28 22:06 UTC by BiancaCristina

- Implementação de um semáforo para controlar o acesso à fila
- Implementação do scheduler para o consumo da fila

2020-11-28 23:48 UTC, rafael2ll requested changes
Sugestão de duas queues para diminuir o impacto, caso exista muitas cópias para fazer no disco

2020-11-28 23:48 UTC, rafael2ll commented on prototype/src/main/java/sd/nosql/prototype/service/impl/QueueServiceImpl.java
> +    public void consumeAll() throws InterruptedException {
Podemos criar 2 queues uma  'oficial' e uma que fica recebendo os requests quando a oficial está bloqueada. Assim, precisariamos de 2 semaforos, uma pra oficial e uma pra de backup, esse segundo só seria ativo quando terminasse a escrita da queue oficial para o banco, onde copiariamos o conteúdo da de backup para a 'oficial', estando duas zonas críticas ativas ao mesmo tempo, com um menor impacto para o usuário, porém.

2020-11-29 01:21 UTC, BiancaCristina commented on prototype/src/main/java/sd/nosql/prototype/service/impl/QueueServiceImpl.java
> +    public void consumeAll() throws InterruptedException {
Fila secundária implementada.

2020-11-29 13:46 UTC, matheuscosta1 approved these changes
ok

2020-11-29 17:28 UTC, rafael2ll approved these changes

2020-11-29 21:03 UTC, rafael2ll commented
Vou tomar a liberdade de mergear para desenvolver os testes :p

2020-11-29 21:03 UTC, merged